version: '3.8'
services:
  nodered:
    image: nodered/node-red:2.2.3-12
    ports:
      - '1880:1880'
    environment:
      - TZ=Australia/Melbourne
    volumes: 
      - "./node-red/data:/data"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - TZ=Australia/Melbourne
      - PGTZ=Australia/Melbourne
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - "./postgresql/data:/var/lib/postgresql/data"