version: '3.8'
services:
  tunnel:
    container_name: tunnel
    hostname: tunnel
    env_file:
      - ./docker.env
    restart: unless-stopped
    # Image for x64 system
    image: cloudflare/cloudflared:latest
    environment:
      - TZ=Australia/Melbourne
    # volumes:
    #   - ./cloudflared/.cloudflared:/etc/cloudflared
    command: 'tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}'
    depends_on:
      - nodered
    networks:
      - app-network

  nodered:
    image: nodered/node-red:2.2.3-12
    restart: unless-stopped
    # Ports not directly exposed, instead thru cloudflare tunnel
    # ports:
    #   - '1880:1880'
    environment:
      - TZ=Australia/Melbourne
    volumes: 
      - "./node-red/data:/data"
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - TZ=Australia/Melbourne
      - PGTZ=Australia/Melbourne
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=C0MP90018#PG
    # ports:
    #   - '5432:5432'
    volumes: 
      - "./postgresql/data:/var/lib/postgresql/data"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge